// See PSTMessage.class for details on these properties
export enum OutlookProperties {
    PR_RTF_COMPRESSED = 0x1009,
    PR_NON_RECEIPT_NOTIFICATION_REQUESTED = 0x0C06,
    PR_ORIGINATOR_NON_DELIVERY_REPORT_REQUESTED = 0x0c08,
    PR_RECIPIENT_TYPE = 0x0c15,
    PR_MESSAGE_CODEPAGE = 0x3FFD,
    PR_INTERNET_CPID = 0x3FDE,
    PR_RTF_SYNC_BODY_CRC = 0x1006,
    PR_RTF_SYNC_BODY_COUNT = 0x1007,
}
